// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Paxi.GraphQL.Demo.Fund.Api.Context;

namespace Paxi.GraphQL.Demo.Fund.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210627011859_Initial Database")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Paxi.GraphQL.Demo.Fund.Api.Model.FixedIncomeFund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("Cota")
                        .HasColumnType("REAL");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("FixedIncomeFunds");
                });

            modelBuilder.Entity("Paxi.GraphQL.Demo.Fund.Api.Model.MultimarketFund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("Cota")
                        .HasColumnType("REAL");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("MultimarketFunds");
                });

            modelBuilder.Entity("Paxi.GraphQL.Demo.Fund.Api.Model.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Paxi.GraphQL.Demo.Fund.Api.Model.FixedIncomeFund", b =>
                {
                    b.HasOne("Paxi.GraphQL.Demo.Fund.Api.Model.Wallet", "Wallet")
                        .WithMany("FixedIncomeFunds")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Paxi.GraphQL.Demo.Fund.Api.Model.MultimarketFund", b =>
                {
                    b.HasOne("Paxi.GraphQL.Demo.Fund.Api.Model.Wallet", "Wallet")
                        .WithMany("MultimarketFunds")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Paxi.GraphQL.Demo.Fund.Api.Model.Wallet", b =>
                {
                    b.Navigation("FixedIncomeFunds");

                    b.Navigation("MultimarketFunds");
                });
#pragma warning restore 612, 618
        }
    }
}
